spring:
  profiles:
    active: native
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rodrigorodes/microservices/
          search-paths:
            - "ms-config-properties/{application}/{profile}"
            - "ms-config-properties/global/{profile}"


            