spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rodrigorodes/microservices/
          search-paths:
            - "ms-config-properties/{application}/{profile}"
